server:
  port: 5000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank_account
  kafka:
    producer:
      bootstrap-servers:
        - locahost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer